name: atm_simulator
description: ATM Simulator.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flex_color_scheme: ^6.1.2
  flutter_bloc: ^8.1.2
  flutter_native_splash: ^2.2.16
  flutter_screenutil: ^5.7.0
  get_it: ^7.2.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.13

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - asset/icon/

flutter_icons:
  android: true
  image_path: "asset/icon/app_icon.png"
  ios: true
  image_path_ios: "asset/icon/app_icon_ios.png"

flutter_native_splash:
  color: "FFFFFF"
  image: "asset/icon/app_icon.png"
  android: true
  ios: true
  web: false
