name: atm_simulator
description: ATM Simulator.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  bloc_test: ^9.1.1
  collection: ^1.17.0
  crypto: ^3.0.2
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  flex_color_scheme: ^6.1.2
  flutter_bloc: ^8.1.2
  flutter_native_splash: ^2.2.16
  flutter_screenutil: ^5.7.0
  get_it: ^7.2.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  hydrated_bloc: ^9.1.0
  mockito: ^5.3.2
  path_provider: ^2.0.13
  sprintf: ^7.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - asset/icon/

flutter_icons:
  android: true
  image_path: "asset/icon/app_icon.png"
  ios: true
  image_path_ios: "asset/icon/app_icon_ios.png"
  web:
    generate: true
    image_path: "asset/icon/app_icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: "asset/icon/app_icon.png"
  android: true
  ios: true
  web: true
