// Mocks generated by Mockito 5.3.2 from annotations
// in atm_simulator/test/app/atm/data/repository/atm_repository_impl_log_in_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:atm_simulator/core/util/pin_encrypter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PinEncrypter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPinEncrypter extends _i1.Mock implements _i2.PinEncrypter {
  @override
  String encrypt(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #encrypt,
          [pin],
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  bool comparePin(
    String? pin,
    String? encryptedPin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #comparePin,
          [
            pin,
            encryptedPin,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}
