name: Play Store Deployment

on: workflow_dispatch

jobs:
  version:
    name: Create Version Number
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Save latest version tag to version.txt
        run: echo ${{ steps.gitversion.outputs.SemVer }} > version.txt

      - name: Upload version.txt
        uses: actions/upload-artifact@v3
        with:
          name: gitversion
          path: version.txt

  build:
    name: Build Appbundle
    needs: version
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version.txt
        uses: actions/download-artifact@v3
        with:
          name: gitversion

      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: version.txt
          trim: true

      - name: Update version in YAML
        run: sed -i '' 's/1.0.0+1/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "16.x"
          cache: gradle

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.3"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Appbundle
        run: flutter build appbundle --obfuscate --split-debug-info=split_debug_info

      - name: Upload Appbundle
        uses: actions/upload-artifact@v3
        with:
          name: android-release
          path: build/app/outputs/bundle/release/app-release.aab

  deploy:
    name: Deploy Appbundle to Play Store
    needs: build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Android Build from artifacts
        uses: actions/download-artifact@v3
        with:
          name: android-release

      - name: Release Build to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.irwancheung.atm_simulator
          releaseFiles: app-release.aab
          track: internal
          status: draft
